// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client.go -package=dockerapi
//

// Package dockerapi is a generated GoMock package.
package dockerapi

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ListContainers mocks base method.
func (m *MockClient) ListContainers(ctx context.Context) ([]Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContainers", ctx)
	ret0, _ := ret[0].([]Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockClientMockRecorder) ListContainers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContainers", reflect.TypeOf((*MockClient)(nil).ListContainers), ctx)
}

// Pull mocks base method.
func (m *MockClient) Pull(ctx context.Context, ref string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, ref)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockClientMockRecorder) Pull(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockClient)(nil).Pull), ctx, ref)
}

// SignalContainer mocks base method.
func (m *MockClient) SignalContainer(ctx context.Context, containerName, signal string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalContainer", ctx, containerName, signal)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalContainer indicates an expected call of SignalContainer.
func (mr *MockClientMockRecorder) SignalContainer(ctx, containerName, signal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalContainer", reflect.TypeOf((*MockClient)(nil).SignalContainer), ctx, containerName, signal)
}

// StartService mocks base method.
func (m *MockClient) StartService(ctx context.Context, composeService string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartService", ctx, composeService)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartService indicates an expected call of StartService.
func (mr *MockClientMockRecorder) StartService(ctx, composeService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartService", reflect.TypeOf((*MockClient)(nil).StartService), ctx, composeService)
}

// StopService mocks base method.
func (m *MockClient) StopService(ctx context.Context, composeService string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopService", ctx, composeService)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopService indicates an expected call of StopService.
func (mr *MockClientMockRecorder) StopService(ctx, composeService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopService", reflect.TypeOf((*MockClient)(nil).StopService), ctx, composeService)
}

// MockComposeRunner is a mock of ComposeRunner interface.
type MockComposeRunner struct {
	ctrl     *gomock.Controller
	recorder *MockComposeRunnerMockRecorder
	isgomock struct{}
}

// MockComposeRunnerMockRecorder is the mock recorder for MockComposeRunner.
type MockComposeRunnerMockRecorder struct {
	mock *MockComposeRunner
}

// NewMockComposeRunner creates a new mock instance.
func NewMockComposeRunner(ctrl *gomock.Controller) *MockComposeRunner {
	mock := &MockComposeRunner{ctrl: ctrl}
	mock.recorder = &MockComposeRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComposeRunner) EXPECT() *MockComposeRunnerMockRecorder {
	return m.recorder
}

// Down mocks base method.
func (m *MockComposeRunner) Down(ctx context.Context, workDir, composeFile string, opts ComposeRunOpts, onStatus StatusFn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Down", ctx, workDir, composeFile, opts, onStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Down indicates an expected call of Down.
func (mr *MockComposeRunnerMockRecorder) Down(ctx, workDir, composeFile, opts, onStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Down", reflect.TypeOf((*MockComposeRunner)(nil).Down), ctx, workDir, composeFile, opts, onStatus)
}

// Images mocks base method.
func (m *MockComposeRunner) Images(ctx context.Context, workDir, composeFile string, opts ComposeRunOpts) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Images", ctx, workDir, composeFile, opts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Images indicates an expected call of Images.
func (mr *MockComposeRunnerMockRecorder) Images(ctx, workDir, composeFile, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Images", reflect.TypeOf((*MockComposeRunner)(nil).Images), ctx, workDir, composeFile, opts)
}

// Pull mocks base method.
func (m *MockComposeRunner) Pull(ctx context.Context, workDir, composeFile string, opts ComposeRunOpts, onStatus StatusFn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, workDir, composeFile, opts, onStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockComposeRunnerMockRecorder) Pull(ctx, workDir, composeFile, opts, onStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockComposeRunner)(nil).Pull), ctx, workDir, composeFile, opts, onStatus)
}

// Services mocks base method.
func (m *MockComposeRunner) Services(ctx context.Context, workDir, composeFile string, opts ComposeRunOpts) ([]ComposeService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Services", ctx, workDir, composeFile, opts)
	ret0, _ := ret[0].([]ComposeService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Services indicates an expected call of Services.
func (mr *MockComposeRunnerMockRecorder) Services(ctx, workDir, composeFile, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Services", reflect.TypeOf((*MockComposeRunner)(nil).Services), ctx, workDir, composeFile, opts)
}

// Up mocks base method.
func (m *MockComposeRunner) Up(ctx context.Context, workDir, composeFile string, opts ComposeRunOpts, onStatus StatusFn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Up", ctx, workDir, composeFile, opts, onStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Up indicates an expected call of Up.
func (mr *MockComposeRunnerMockRecorder) Up(ctx, workDir, composeFile, opts, onStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockComposeRunner)(nil).Up), ctx, workDir, composeFile, opts, onStatus)
}
