package nginxcfg

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// OverlayFileName is the sibling compose file that adds host.docker.internal.
const OverlayFileName = "docker-compose.msc.yml"

// DefaultNginxService is the compose service name used for reload and overlay.
const DefaultNginxService = "nginx"

// HasHostGateway reports whether compose YAML already maps host.docker.internal.
func HasHostGateway(content string) bool {
	return strings.Contains(content, "host.docker.internal:host-gateway") ||
		strings.Contains(content, "host.docker.internal: host-gateway")
}

// OverlayYAML is a compose overlay that defines host.docker.internal via host-gateway.
func OverlayYAML(nginxService string) string {
	if nginxService == "" {
		nginxService = DefaultNginxService
	}
	return fmt.Sprintf(`# Generated by msc so Source Mode works on native Linux Engine.
# Redundant but harmless on Docker Desktop.
services:
  %s:
    extra_hosts:
      - "host.docker.internal:host-gateway"
`, nginxService)
}

// OverlayPath is the sibling overlay next to the project's compose file.
func OverlayPath(composeFile string) string {
	return filepath.Join(filepath.Dir(composeFile), OverlayFileName)
}

// EnsureHostGateway writes a sibling overlay when the main compose file lacks host-gateway.
func EnsureHostGateway(root, composeFile string) (path string, wrote bool, err error) {
	abs := composeFile
	if !filepath.IsAbs(composeFile) {
		abs = filepath.Join(root, composeFile)
	}
	data, err := os.ReadFile(abs)
	if err != nil {
		return "", false, fmt.Errorf("read compose file %s: %w", abs, err)
	}
	if HasHostGateway(string(data)) {
		return "", false, nil
	}
	overlay := OverlayPath(abs)
	if existing, err := os.ReadFile(overlay); err == nil && HasHostGateway(string(existing)) {
		return overlay, false, nil
	}
	if err := os.WriteFile(overlay, []byte(OverlayYAML(DefaultNginxService)), 0o644); err != nil {
		return "", false, fmt.Errorf("write %s: %w", overlay, err)
	}
	return overlay, true, nil
}
