package nginxcfg

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/SoheilHasankhani/msc-cli/internal/manifest"
	"github.com/SoheilHasankhani/msc-cli/internal/state"
)

const overlayHeader = `# generated by msc — do not edit
# Docker vs Source upstreams. Rewritten by isos up / isos switch.
`

var overlayMapRE = regexp.MustCompile(`(?s)map\s+""\s+\$([A-Za-z0-9_]+)\s*\{[^}]*?\bdefault\s+(\S+);`)

// OverlayService is one Manifest service written into the generated overlay.
type OverlayService struct {
	ComposeService string
	SourcePort     int
}

// OverlayServices lists Manifest compose services in stable order.
func OverlayServices(m *manifest.Manifest) []OverlayService {
	if m == nil {
		return nil
	}
	var out []OverlayService
	for _, repo := range m.Repos {
		for _, svc := range repo.Services {
			if svc.ComposeService == "" {
				continue
			}
			out = append(out, OverlayService{ComposeService: svc.ComposeService, SourcePort: svc.SourcePort})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ComposeService < out[j].ComposeService })
	return out
}

// RenderOverlay builds the generated maps file for the given modes.
// Missing modes default to Docker.
func RenderOverlay(services []OverlayService, modes map[string]state.Mode) string {
	var b strings.Builder
	b.WriteString(overlayHeader)
	for _, svc := range services {
		mode := modes[svc.ComposeService]
		if mode != state.ModeSource {
			mode = state.ModeDocker
		}
		url := DockerUpstream(svc.ComposeService)
		if mode == state.ModeSource {
			url = SourceUpstream(svc.SourcePort)
		}
		fmt.Fprintf(&b, "\nmap \"\" $%s {\n    default %s;\n}\n", UpstreamVar(svc.ComposeService), url)
	}
	return b.String()
}

// ParseOverlayModes reads current modes from a generated overlay.
func ParseOverlayModes(content string, services []OverlayService) map[string]state.Mode {
	urls := parseOverlayURLs(content)
	out := map[string]state.Mode{}
	for _, svc := range services {
		url, ok := urls[UpstreamVar(svc.ComposeService)]
		if !ok {
			continue
		}
		out[svc.ComposeService] = classifyUpstream(url, svc.ComposeService, svc.SourcePort)
	}
	return out
}

func parseOverlayURLs(content string) map[string]string {
	out := map[string]string{}
	for _, m := range overlayMapRE.FindAllStringSubmatch(content, -1) {
		out[m[1]] = strings.TrimSuffix(m[2], ";")
	}
	return out
}

func classifyUpstream(url, composeService string, port int) state.Mode {
	if strings.Contains(url, "host.docker.internal:"+strconv.Itoa(port)) ||
		strings.Contains(url, "host.docker.internal") {
		return state.ModeSource
	}
	host := strings.TrimPrefix(strings.TrimPrefix(url, "http://"), "https://")
	if i := strings.Index(host, ":"); i >= 0 {
		host = host[:i]
	}
	for _, c := range HostCandidates(composeService) {
		if host == c {
			return state.ModeDocker
		}
	}
	return state.ModeDocker
}

// ReadOverlayTarget reports the live nginx target for a compose service.
func ReadOverlayTarget(content, composeService string, port int) string {
	urls := parseOverlayURLs(content)
	url, ok := urls[UpstreamVar(composeService)]
	if !ok {
		return ""
	}
	if classifyUpstream(url, composeService, port) == state.ModeSource {
		return state.NginxSourceTarget(port)
	}
	return state.NginxTargetContainer
}

// WriteOverlay writes the generated maps file, preserving existing modes.
// If composeService is non-empty, that service is set to `to`.
func WriteOverlay(path string, services []OverlayService, composeService string, to state.Mode) error {
	if composeService != "" {
		if to != state.ModeDocker && to != state.ModeSource {
			return fmt.Errorf("unsupported mode %q", to)
		}
		found := false
		for _, svc := range services {
			if svc.ComposeService == composeService {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("no nginx upstream found for %q", composeService)
		}
	}

	modes := map[string]state.Mode{}
	if data, err := os.ReadFile(path); err == nil {
		modes = ParseOverlayModes(string(data), services)
	}
	if composeService != "" {
		modes[composeService] = to
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(RenderOverlay(services, modes)), 0o644)
}

// EnsureOverlay creates or refreshes the generated file without changing known modes.
func EnsureOverlay(path string, services []OverlayService) error {
	return WriteOverlay(path, services, "", "")
}

// SourceModeNames returns compose services currently routed to Source Mode.
func SourceModeNames(overlayPath string, services []OverlayService) []string {
	data, err := os.ReadFile(overlayPath)
	if err != nil {
		return nil
	}
	modes := ParseOverlayModes(string(data), services)
	var names []string
	for _, svc := range services {
		if modes[svc.ComposeService] == state.ModeSource {
			names = append(names, svc.ComposeService)
		}
	}
	return names
}
