// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock_runner.go -package=gitops
//

// Package gitops is a generated GoMock package.
package gitops

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockRunner) Clone(ctx context.Context, repoURL, destPath string, progress io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, repoURL, destPath, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockRunnerMockRecorder) Clone(ctx, repoURL, destPath, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockRunner)(nil).Clone), ctx, repoURL, destPath, progress)
}

// LsRemote mocks base method.
func (m *MockRunner) LsRemote(ctx context.Context, repoURL string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LsRemote", ctx, repoURL)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LsRemote indicates an expected call of LsRemote.
func (mr *MockRunnerMockRecorder) LsRemote(ctx, repoURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LsRemote", reflect.TypeOf((*MockRunner)(nil).LsRemote), ctx, repoURL)
}

// Pull mocks base method.
func (m *MockRunner) Pull(ctx context.Context, repoPath string, progress io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, repoPath, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockRunnerMockRecorder) Pull(ctx, repoPath, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockRunner)(nil).Pull), ctx, repoPath, progress)
}
